#!/usr/bin/env bash

alias simplehttpserver="python -m SimpleHTTPServer"
alias rubyhttp="ruby -run -e httpd -- -p 8000 ."

# Git aliases
alias gst="git status"
alias gdiff='git diff --compaction-heuristic'
complete -o default -o nospace -F _git_diff gdiff
alias changes="git diff --name-only master origin/master"
alias gsubup="git submodule update --recursive --remote"

# Rails aliases
alias rg="./bin/rails generate"
alias bex="bundle exec"

# typo aliases
alias brwe=brew

# tmux aliases
alias tmattach="tmux -CC new -A -s"
